### ISSUE TITLE
error reading config file at circle.yml: open .circleci/config.yml: no such file or directory

### ISSUE THREAD

**Issue by stephenmathieson** [circleci/local-cli#17]
I've got a repository with a `circle.yml` file in its topmost directory. Builds work fine on circleci.com, but I get this error when trying to run them locally:

```
$ circleci build

FATA[2018-05-25T15:43:44Z] failed to compute task config                 error="error reading config file at circle.yml: open .circleci/config.yml: no such file or directory"
```

Would it be possible to add support for `./circle.yml` rather than enforcing `./.circle/config.yml`?

**Comment by felicianotech** [comment]
`./circle.yml` is a CircleCI 1.0 configuration file. The CircleCI Local CLI is a tool for CircleCI 2.0 so that will not be supported.

**Comment by stephenmathieson** [comment]
Hmm, ok. IMO since the webapp supports it, it'd be really nice if the local tool did too, but I understand not wanting to maintain multiple code paths.

Oh well, thanks anyway!

**Comment by dnephin** [comment]
You can set the path to the config file yourself, if you want, with the `-c` flag.

**Comment by stephenmathieson** [comment]
Thanks Daniel, I must have overlooked that flag!

**Comment by felicianotech** [comment]
@stephenmathieson CircleCI 1.0 will be EOL and thus won't run by the end of August. This is why we can't justify adding support.

@dnephin Still won't run. The Local CLI can't build CircleCI 1.0 projects.

**Comment by stephenmathieson** [comment]
@felicianotech my `./circle.yml` file contains v2 configuration

**Comment by felicianotech** [comment]
@stephenmathieson Really? Oh okay that's strange. Then yes that changes everything. The flag Daniel pointed out will work for you then. Sorry, that's the default filename for 1.0 so I thought it was a 1.0 config.

**Comment by stephenmathieson** [comment]
Cool, thanks for clarifying!
