### ISSUE TITLE
`circleci tests` writes \r\n-delimited lines and fails to handle such a delimiter

### ISSUE THREAD

**Issue by exarkun** [circleci/local-cli#18]
Consider:

```
$ circleci tests glob --verbose "src/**/test_*.py" > all_files.txt
$ python -c 'print(repr(open("all_files.txt").read(100)))'
'\nsrc/allmydata/test/mutable/test_problems.py\r\nsrc/allmydata/test/mutable/test_filenode.py\r\nsrc/allmy'
```

Not great since all my Linux line-oriented tools believe that \n is the correct line delimiter.  But worse:

```
$ python -c 'print(repr(open("some_files.txt").read(100)))'
'\nsrc/allmydata/test/cli/test_alias.py\r\r\nsrc/allmydata/test/cli/test_backup.py\r\r\nsrc/allmydata/test/c'
```

Now the lines are \r\r\n delimited!

Also, what's with the leading \n?

The lines should be \n delimited in all cases because this is how text files work on POSIX.

**Comment by dnephin** [comment]
I can't reproduce this problem. There's nothing in the `tests glob` command that would add `\r\n` unless you're running it on windows. I tried it myself (using those python commands) and did not see any `\r`. This must be a configuration issue with whatever version of python you are using.

**Comment by exarkun** [comment]
I didn't say, but surely should have, that I installed circleci using the snap instructions here:

   https://circleci.com/docs/2.0/local-cli/#alternative-installing-ubuntu-1604-or-ubuntu-1704

And I'm on Ubuntu 17.10

**Comment by zzak** [comment]
Hello @exarkun!

Great name by the way, a classic sith tale :)

Since we're unable to reproduce this outside of the CLI, would you mind opening a ticket on [the new CLI issue tracker](https://github.com/CircleCI-Public/circleci-cli/issues/new) with a reproduction?

Thanks!
