### ISSUE TITLE
circleci config validate does not check that jobs listed in a workflow are defined

### ISSUE THREAD

**Issue by federicobond** [circleci/local-cli#20]
When a job is listed in a workflow but missing from the jobs section, the config validator will report the config as valid but will fail immediately when pushed to CircleCI:

```
* Cannot find a job named `build` to run in the `jobs:` section of your configuration file.
```

The validator should ensure that all jobs listed in workflows are actually defined.

**Comment by felicianotech** [comment]
@marcomorain Thoughts here?

**Comment by marcomorain** [comment]
We are working on a new CLI tool that will do full config validation server-side. You can follow progress at https://github.com/CircleCI-Public/circleci-cli. I'll move this issue there.

**Comment by marcomorain** [comment]
https://github.com/CircleCI-Public/circleci-cli/issues/11

**Comment by marcomorain** [comment]
@felicianotech you can close this issue 👌

**Comment by federicobond** [comment]
Thanks!
