### ISSUE TITLE
Shouldn't checkout step ignore .gitignored files?

### ISSUE THREAD

**Issue by strindhaug** [circleci/local-cli#37]
Shouldn't the circleci command ignore files in the local repo that are ignored by gitignore?
I'm having an issue testing locally in a repo where if the generated android build files and the node_modules files (both of which are ignored by `.gitignore`) are in the local repo when i run `circleci build` it fails on the checkout step trying to copy these files:

```
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/my-company/the-project && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/my-company/the-project
cp: cannot access ‘/tmp/_circleci_local_build_repo/./node_modules/react-native-auth0/android/build/generated/source/r/release/com’: Permission denied
cp: cannot access ‘/tmp/_circleci_local_build_repo/./node_modules/react-native-background-service/android/build/generated/source/r/release/com’: Permission denied
cp: cannot access ‘/tmp/_circleci_local_build_repo/./node_modules/react-native-background-timer/android/build/generated/source/r/release/com’: Permission denied
...etc
```
If I delete these folders (or move them outside the repo) the command succeeds, but having to do this all the time is really impractical. I would have thought that the command should ignore gitignored files so that the build environment is most like how it will be when actually running on circleci.com so why isn't it ignoring these files?

And even if it's deliberately doing this because it's useful in some cases, why does failing to read an ignored file cause the checkout step to fail, could it not at least just ignore errors when trying to read ignored files? (In my case these will be either be overwritten later in the script or they are completely irrelevant for the tests anyway)

Or is there maybe a `.circleciignore`-file or something similar I could use?

**Comment by dnephin** [comment]
Right now the "local checkout" step is just a simple copy of all files. It should probably use `git ls-files` or `git archive` to build a tarball and use that as the context of the build.

**Comment by marcomorain** [comment]
This is now tracked at https://github.com/CircleCI-Public/circleci-cli/issues/151
