### ISSUE TITLE
Checkout Error on "circleci local execute"

### ISSUE THREAD

**Issue by JinbinLiang** [circleci/local-cli#39]
Hi everyone,

I'm meeting an issue that occurred previously. When I run "circleci local execute" on my Mac with my docker image from Docker hub, it showed error message as below.
```
====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /home/circleci/backend2 && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/backend2
cp: cannot stat '/tmp/_circleci_local_build_repo/.': No such file or directory
Error: Exited with code 1
Step failed
Error: runner failed
Task failed
```
I have tried "circleci version" and "circleci update", but it doesn't work. Here are the versions of circleci cli and docker respectively.
```
circleci version
0.1.2191+af75d4d

docker version
Client:
Version: 18.06.1-ce
API version: 1.38
Go version: go1.10.3
Git commit: e68fc7a
Built: Tue Aug 21 17:21:31 2018
OS/Arch: darwin/amd64
Experimental: false

Server:
Engine:
Version: 18.06.1-ce
API version: 1.38 (minimum version 1.12)
Go version: go1.10.3
Git commit: e68fc7a
Built: Tue Aug 21 17:29:02 2018
OS/Arch: linux/amd64
Experimental: true
```
Could anyone give me any advices, please? Cheers.

**Comment by zzak** [comment]
Thanks for your report @JinbinLiang!

If you are able to provide more feedback to help us debug this issue, please file a report on [the new CLI issue tracker](https://github.com/CircleCI-Public/circleci-cli/issues/new). :bow:
