### ISSUE TITLE
Support workflows

### ISSUE THREAD

**Issue by ewirch** [circleci/local-cli#5]
The [documentation](https://circleci.com/docs/2.0/local-cli/) says:

> **Note**: The Local CLI does not yet support Workflows.

Please add support for workflows.

**Comment by felicianotech** [comment]
It's in the works.

**Comment by vpereira** [comment]
any status or ETA on that?

**Comment by felicianotech** [comment]
Not that I know of no. This CLI is being superseded by a more feature-full CLI in the future (probably sometime this year). That new CLI is likely where the Workflow support will land. Our blog and CircleCI Discuss is the best places to watch for when that happens.
