### ISSUE TITLE
Respect XDG for config/cache/data file locations.

### ISSUE THREAD

**Issue by jasonkarns** [circleci/local-cli#9]
It appears that circleci is presently writing files to ~/.circleci.

The XDG basedir spec specifies where config, cache, and data files should be written: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

`$XDG_CONFIG_HOME`, `$XDG_CACHE_HOME`, and `$XDG_DATA_HOME` respectively. Each of those has their default values for when the env vars aren't set: 

- config: `$HOME/.config`
- cache: `$HOME/.cache`
- data: `$HOME/.local/share`

Currently, my ~/.circleci directory contains: current_picard_digest  latest_picard_digest

Which, I'm presuming are cache-like files? (They're fungible?)

Thus, they should be written to: `${XDG_CACHE_HOME:-$HOME/.cache}/circleci/`

**Comment by zzak** [comment]
Thank you for the feedback @jasonkarns!

I have created a card in our backlog to try and address this.
